language: node_js
deploy:
  api_key:
    secure: XiWwAJlblsK9zmbRyA0KtOfv9lwQ5ftlHodY/cQvxQj9DFmP1hfnPqGihijkAEAgG+P6bj/rg9qzXSUqNIA9VrKMk4idFo2bP2GQwktRgmuXHvfm1flvaKe8Vwl3b355LRLOccfEWiG0KIexCiGIwwmG/KMmk41DcMTgAeTZQ8Y=
  provider: npm
  email: john@mclear.co.uk
